import React, { useState } from 'react';
import { Badge } from '../components/common/Badge';
import { Modal } from '../components/common/Modal';
import { FileCode, Download, Trash2, Eye, Upload, Search, FileText } from 'lucide-react';

export function Files({ files = [] }) {
  const [selectedFile, setSelectedFile] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');

  const filteredFiles = files.filter(f => f.name.toLowerCase().includes(searchQuery.toLowerCase()));

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-2 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-mono text-indigo-400 uppercase tracking-wider font-bold">WORKSPACE ARTIFACTS</span>
            <Badge status={`${files.length} Files`} />
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight mt-1">Generated Files & Assets</h1>
          <p className="text-xs text-slate-400">Code modules, design tokens, marketing copy, and compiled PDFs generated by agents.</p>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search files..."
              className="bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-4 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 w-64"
            />
          </div>
        </div>
      </div>

      <div className="glass-panel rounded-2xl p-6 border border-slate-800">
        {filteredFiles.length === 0 ? (
          <div className="text-center py-12 text-slate-500 text-xs font-mono">
            No files generated yet. Run a goal in the workspace to generate source code and artifacts.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {filteredFiles.map(file => (
              <div key={file.id} className="p-4 rounded-xl glass-card border border-slate-800 hover:border-indigo-500/50 space-y-3 transition-all">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <FileCode className="w-5 h-5 text-indigo-400" />
                    <div>
                      <h4 className="font-bold text-xs text-white truncate max-w-[150px]">{file.name}</h4>
                      <span className="text-[10px] font-mono text-slate-500 uppercase">{file.type || 'code'}</span>
                    </div>
                  </div>
                  <span className="text-[10px] font-mono text-slate-400">{file.size || '2.4 KB'}</span>
                </div>

                <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800">
                  <button
                    onClick={() => setSelectedFile(file)}
                    className="p-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-white transition-colors"
                    title="Preview File"
                  >
                    <Eye className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* File Inspector Modal */}
      <Modal
        isOpen={!!selectedFile}
        onClose={() => setSelectedFile(null)}
        title={selectedFile ? `File Preview: ${selectedFile.name}` : ''}
      >
        {selectedFile && (
          <div className="space-y-4">
            <div className="flex justify-between items-center text-xs font-mono text-slate-400">
              <span>File Type: {selectedFile.type}</span>
              <span>Size: {selectedFile.size}</span>
            </div>
            <pre className="p-4 bg-slate-950 rounded-xl border border-slate-800 font-mono text-xs text-indigo-200 overflow-x-auto max-h-96 whitespace-pre-wrap">
              {selectedFile.content || '// Content snippet compiled by AI agent.'}
            </pre>
          </div>
        )}
      </Modal>
    </div>
  );
}
