import React, { useState } from 'react';
import { Badge } from '../common/Badge';
import { Modal } from '../common/Modal';
import { Bot, Clock, ArrowDown, ArrowRight, ShieldAlert, CheckCircle2, Play, AlertCircle } from 'lucide-react';

export function TaskGraph({ subtasks = [], onSelectSubtask }) {
  const [selectedSubtask, setSelectedSubtask] = useState(null);

  if (!subtasks || subtasks.length === 0) {
    return (
      <div className="glass-panel rounded-2xl p-8 text-center border border-slate-800">
        <p className="text-slate-400 text-xs font-mono">No subtasks generated yet. Submit a goal to see the visual workflow tree.</p>
      </div>
    );
  }

  const getNodeColor = (status) => {
    switch (status) {
      case 'completed': return 'border-emerald-500/50 bg-emerald-950/20 text-emerald-300';
      case 'in_progress': return 'border-indigo-500 bg-indigo-950/40 text-indigo-300 animate-pulse-glow';
      case 'awaiting_approval': return 'border-amber-500 bg-amber-950/30 text-amber-300';
      case 'failed': return 'border-rose-500 bg-rose-950/30 text-rose-300';
      default: return 'border-slate-800 bg-slate-900/60 text-slate-400';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'completed': return <CheckCircle2 className="w-4 h-4 text-emerald-400" />;
      case 'in_progress': return <Play className="w-4 h-4 text-indigo-400 fill-current animate-pulse" />;
      case 'awaiting_approval': return <ShieldAlert className="w-4 h-4 text-amber-400" />;
      case 'failed': return <AlertCircle className="w-4 h-4 text-rose-400" />;
      default: return <Clock className="w-4 h-4 text-slate-500" />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Graph Visual Canvas */}
      <div className="glass-panel rounded-2xl p-6 border border-slate-800 relative overflow-x-auto">
        <div className="flex items-center justify-between mb-6 pb-3 border-b border-slate-800">
          <div>
            <h3 className="text-sm font-bold text-white tracking-wide flex items-center gap-2">
              <span>Autonomous Execution Plan & Dependency Graph</span>
            </h3>
            <p className="text-xs text-slate-400">Structured workflow generated by AI Planner agent</p>
          </div>
          <span className="text-xs font-mono px-3 py-1 rounded-full bg-slate-900 text-slate-400 border border-slate-800">
            {subtasks.length} Subtasks
          </span>
        </div>

        {/* Tree Render */}
        <div className="flex flex-col items-center gap-6 min-w-[700px] py-4">
          {subtasks.map((task, index) => {
            const hasDependencies = task.dependencies && task.dependencies.length > 0;
            const nodeStyle = getNodeColor(task.status);

            return (
              <React.Fragment key={task.id}>
                {/* Arrow Connector */}
                {index > 0 && (
                  <div className="flex flex-col items-center my-[-8px]">
                    <div className="w-0.5 h-6 bg-gradient-to-b from-indigo-500/50 to-slate-700" />
                    <ArrowDown className="w-4 h-4 text-indigo-400" />
                  </div>
                )}

                {/* Task Node */}
                <div
                  onClick={() => setSelectedSubtask(task)}
                  className={`w-full max-w-xl p-4 rounded-xl border ${nodeStyle} cursor-pointer transition-all hover:scale-[1.01] shadow-xl relative group`}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5">{getStatusIcon(task.status)}</div>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="font-semibold text-xs text-white tracking-wide">{task.name}</span>
                          <Badge status={task.status} size="sm" />
                        </div>
                        <p className="text-xs text-slate-400 mt-1 line-clamp-2">{task.description}</p>
                      </div>
                    </div>

                    <div className="text-right flex flex-col items-end gap-1">
                      <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-slate-950 text-indigo-300 border border-slate-800 flex items-center gap-1">
                        <Bot className="w-3 h-3 text-indigo-400" />
                        {task.agentId}
                      </span>
                      {task.estDuration && (
                        <span className="text-[10px] text-slate-500 font-mono flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {task.estDuration}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Dependency details pill */}
                  {hasDependencies && (
                    <div className="mt-2.5 pt-2 border-t border-slate-800/60 flex items-center gap-2 text-[10px] text-slate-400 font-mono">
                      <span>Requires:</span>
                      {task.dependencies.map(depId => (
                        <span key={depId} className="px-1.5 py-0.5 rounded bg-slate-950 border border-slate-800 text-slate-300">
                          {depId}
                        </span>
                      ))}
                    </div>
                  )}

                  {/* Approval requirement indicator */}
                  {task.requiresApproval && (
                    <div className="absolute top-[-8px] right-4 bg-amber-500 text-slate-950 font-bold text-[9px] font-mono px-2 py-0.5 rounded-full shadow-lg flex items-center gap-1">
                      <ShieldAlert className="w-3 h-3" />
                      Approval Required
                    </div>
                  )}
                </div>
              </React.Fragment>
            );
          })}
        </div>
      </div>

      {/* Subtask Inspector Modal */}
      <Modal
        isOpen={!!selectedSubtask}
        onClose={() => setSelectedSubtask(null)}
        title={selectedSubtask ? `Task Detail: ${selectedSubtask.name}` : ''}
      >
        {selectedSubtask && (
          <div className="space-y-4 text-xs">
            <div className="flex items-center justify-between bg-slate-900 p-3 rounded-xl border border-slate-800">
              <div>
                <span className="text-slate-400 font-mono">Status:</span>
                <div className="mt-1"><Badge status={selectedSubtask.status} /></div>
              </div>
              <div>
                <span className="text-slate-400 font-mono">Assigned Agent:</span>
                <p className="font-bold text-white capitalize mt-0.5">{selectedSubtask.agentId} Agent</p>
              </div>
              <div>
                <span className="text-slate-400 font-mono">Priority:</span>
                <p className="font-bold text-indigo-400 uppercase mt-0.5">{selectedSubtask.priority || 'Medium'}</p>
              </div>
            </div>

            <div>
              <h4 className="font-semibold text-slate-300 mb-1">Description</h4>
              <p className="text-slate-400 bg-slate-950 p-3 rounded-xl border border-slate-800 leading-relaxed">
                {selectedSubtask.description}
              </p>
            </div>

            {selectedSubtask.output && (
              <div>
                <h4 className="font-semibold text-emerald-400 mb-1">Execution Output</h4>
                <pre className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-slate-300 font-mono whitespace-pre-wrap overflow-x-auto max-h-60">
                  {selectedSubtask.output}
                </pre>
              </div>
            )}

            {selectedSubtask.toolResult && (
              <div>
                <h4 className="font-semibold text-indigo-400 mb-1">Tool Execution Result</h4>
                <pre className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-indigo-300 font-mono overflow-x-auto">
                  {JSON.stringify(selectedSubtask.toolResult, null, 2)}
                </pre>
              </div>
            )}
          </div>
        )}
      </Modal>
    </div>
  );
}
